version: '3.8'

services:
  # Nginx 反向代理
  nginx:
    image: nginx:1.27-alpine
    container_name: ${PROJECT_PREFIX}_nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - sp_default

  # Next.js Web应用 - 使用本地构建的镜像
  web:
    image: scriptparser-web-local:latest
    container_name: ${PROJECT_PREFIX}_frontend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    expose:
      - "3000"
    networks:
      - sp_default

networks:
  sp_default:
    driver: bridge
    name: ${PROJECT_PREFIX}_default
