services:
  # Nginx 反向代理
  nginx:
    image: nginx:1.27-alpine
    container_name: scriptparser-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - coprocessor
    networks:
      - scriptparser-network

  # Next.js Web应用
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost/api
    container_name: scriptparser-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
    expose:
      - "3000"
    networks:
      - scriptparser-network

  # FastAPI AI协处理器
  coprocessor:
    build:
      context: ./apps/coprocessor
      dockerfile: Dockerfile
    container_name: scriptparser-coprocessor
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    env_file:
      - ./apps/coprocessor/.env
    expose:
      - "8000"
    networks:
      - scriptparser-network

networks:
  scriptparser-network:
    driver: bridge

volumes:
  nginx_logs: